sample_app/config/routes.rb
Rails.application.routes.draw do

    root 'static_pages#home'
    # using the get '/help', to: 'static_pages#help'
    # rails creates to paths the 
    # help_path -> '/help'  AND THE help_url -> 'http://www.example.com/help'

    get '/help',        to: 'static_pages#help'
    get '/about',       to: 'static_pages#about'
    get '/contact',     to: 'static_pages#contact'
    get '/signup',      to: 'users#new'    
    get '/login',       to: 'sessions#new'
    post '/login',      to: 'sessions#create'
    delete 'logout',     to: 'sessions#destroy'
    resources :users

    # Note: get 'static_pages/help' make a symbol avaialble
    # such as, static_pages_help_url


    # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

sample_app/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

sample_app/app/models/user.rb
class User < ApplicationRecord
    # Validations are used to ensure that only valid data is saved
    # into your database.

    #attr_accessor creates User.remember_token access for get and set
    attr_accessor :remember_token
    # callback method gets invoked by Active Record
    # before_save { self.email = email.downcase }  
    before_save { email.downcase! }
    validates(:name, presence: true, length: {maximum: 50})

    # (below)  more info on Rubular website,
    #  OR pg 275 Ruby on Rails Tutorial
    VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-]+(\.[a-z\d\-]+)*\.[a-z]+\z/i
    validates(:email, presence: true, length: {maximum: 255},
              format: { with: VALID_EMAIL_REGEX },
              uniqueness:{case_sensitive: false})
    # requires bcrypt and user table have column password_digest 
    has_secure_password
    validates :password, presence: true, length: {minimum: 6}

    # Returns the hash digest of the given string.
    # Used in tests therfore the cost is set to minimum
    def User.digest(string)
      cost = ActiveModel::SecurePassword.min_cost ?
             BCrypt::Engine::MIN_COST :
             BCRYPT::Engine.cost
      BCrypt::Password.create(string, cost: cost)
    end

    # Returns a random token.
    def User.new_token
      SecureRandom.urlsafe_base64
    end

    def remember
      self.remember_token = User.new_token
          update_attribute(:remember_digest, User.digest(remember_token))
    end

    # Returns true if a given token matches a digest
    def authenticated?(remember_token)
      return false if remember_digest.nil?
      BCrypt::Password.new(remember_digest).is_password?(remember_token)
    end

    # Forgets a user.
    def forget
      update_attribute(:remember_digest, nil)
    end
end

sample_app/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
        # Built-in mechanism for preventing CSRF
    protect_from_forgery with: :exception
    
        # Stores temp cookies which are destroyed
        # upon the user closing the browser
        # Because it is in ApplicationConroller
        #  SessionHelper available in all views
    include SessionsHelper

end

sample_app/app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

  def create
        #Read teh paramerters passed by a form and try to 
        #log a user in by verifying the user entered password
      user = User.find_by(email: params[:session][:email].downcase)
      if user && user.authenticate(params[:session][:password])
          log_in user       # defined in sessions_helper
          remember user     # defined in sessions_helper
          redirect_to user  # automatically routes to user's profile page
      else
          flash.now[:danger] = 'Invalid email/password combination'
          # Create an error message
          render 'new'
      end
  end

  def destroy
    log_out if logged_in?
    redirect_to root_url
  end
end

sample_app/app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home
  end

  def help
  end

  def about
  end
end

sample_app/app/controllers/users_controller.rb
class UsersController < ApplicationController
 
  def show
    @user = User.find(params[:id])

    # the dubugger opens a active debuggin console 
    # in the rails server terminal used to view
    # all data and instance variables active in the 
    # program
    #debugger        # provided by the byebug gem
  end
    
  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)         
    if @user.save
      log_in @user
      flash[:success] = "Welcome to the Sample App!"
      # (BELOW) equivalent redirect_to user_url(@user).
      # automatically loads the users/show page.
      redirect_to @user
    else
      render 'new'
    end
  end

      
  private 
      def user_params
        params.require(:user).permit(:name, :email,
                                     :password,
                                     :password_confirmation)
      end
end

sample_app/app/helpers/application_helper.rb
module ApplicationHelper

    # Returns the full title on a per-page basis.
    def full_title(page_title = '')
        base_title = "Ruby on Rails Tutorial Sample App"
        if page_title.empty?
            base_title
        else
            page_title + " | " + base_title
        end 
    end
end

sample_app/app/helpers/sessions_helper.rb
module SessionsHelper

    # Logs in the given user
    def log_in(user)
        # Places a temp cookie on the user's browser
        # containing an encrypted version of the
        # user's id.
        session[:user_id] = user.id
    end

    def remember(user)
      user.remember
      cookies.permanent.signed[:user_id] = user.id
      cookies.permanent[:remember_token] = user.remember_token
    end


    # Returns the user corresponding to the remember token cookie
    # if a user is not currently logged on with a session[:user_id]
    def current_user
      if (user_id = session[:user_id])
        @current_user ||= User.find_by(id: user_id)
      elsif (user_id = cookies.signed[:user_id])
        user = User.find_by(id: user_id)
        if user && user.authenticated?(cookies[:remember_token])
          log_in user
          @current_user = user
        end
      end
    end

    # Returns true if the user is logged in, false otherwise.
    def logged_in?
      !current_user.nil?
    end

    # Forgets a persistent session
    def forget(user)
      user.forget
      cookies.delete(:user_id)
      cookies.delete(:remember_token)
    end

    # Logs out the current user.
    def log_out
        forget(current_user)
      session.delete(:user_id)
      @current_user = nil
    end
end

sample_app/app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

sample_app/app/helpers/users_helper.rb
module UsersHelper

    # Returns the Gravatar for the given user.
    def gravatar_for(user)
        gravatar_id = Digest::MD5::hexdigest(user.email.downcase)
        gravatar_url = "https://secure.gravatar.com/avatar/#{gravatar_id}"
        image_tag(gravatar_url, alt: user.name, class: "gravatar")
    end
       # (ABOVE) Gravatar URLs are based on MD5 hash of the users's email
       # address.  Gravatar is a free service that allows users to upload
       # images and associate them with eamil addresses they control.
       # Gravatars are a convenient way to include user profile images 
       # without going throught the trouble of managing image upload,
       # cropping, and storage */
end

sample_app/app/views/layouts/_footer.html.erb
<footer class="footer">
    <small>
        The <a href="http://www.railstutorial.org/">Ruby on Rails
            Tutorial</a>
        by <a href="http://www.michaelhartl.com/">Michael Hartl</a>
    </small>
    <nav>
        <ul>
            <li><%= link_to "About", about_path %></li>
            <li><%= link_to "Contact", contact_path %></li>
            <li><a href="http://news.railstutorial.org/">News</a></li>
        </ul>
    </nav>
</footer>

sample_app/app/views/layouts/_header.html.erb
<header class="navbar navbar-fixed-top navbar-inverse">
  <div class="container">
    <%= link_to "sample app", root_path, id: "logo" %>
    <nav>
        <ul class="nav navbar-nav navbar-right">
            <li><%= link_to "Home", root_path %></li>
            <li><%= link_to "Help", help_path %></li>
            <% if logged_in? %>
              <li><%= link_to "Users", "#" %></li>
              <li class="dropdown">
                <a href="#" class="dropdown-toggle"
                            data-toggle="dropdown">
                     Account <b class="caret"></b>
                </a>
                <ul class="dropdown-menu"> <%# part of BootStraps JS library %>
                  <li><%= link_to "Profile", current_user %></li>
                  <li><%= link_to "Settings", "#" %></li>
                  <li class="divider"></li>
                  <li><%= link_to "Log out", logout_path,
                                             method: "delete" %>
                  </li>
                </ul>
              </li>
            <% else %>
              <li><%= link_to "Log in", login_path %></li>
            <% end %>
        </ul>
    </nav>
  </div>
</header>

sample_app/app/views/layouts/_shim.html.erb
<!--[if lt IE 9]>
    <script src="cdnjs.cloudflare.com/ajax/libs/html5shiv/r29/html5.min.js">
    </script>
<![endif]-->

sample_app/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= full_title(yield(:title)) %></title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <%= render 'layouts/shim' %>
  </head>
  <body>
      <%= render 'layouts/header' %>
      <div class="container">
          <% flash.each do |message_type, message| %>
              <div class="alert alert-<%= message_type %>">
                  <%= message %>
              </div>
          <% end %>
          <%= yield %>
          <%= render 'layouts/footer' %>
          <%= debug(params) if Rails.env.development? %>
      </div>
  </body>
</html>

sample_app/app/views/shared/_error_messages.html.erb
<% if @user.errors.any? %>
    <div id="error_explanation">
        <div class="alert alert-danger">
            The form contains <%= pluralize(@user.errors.count,
                                             "error") %>
        </div>
<%# After an invalid form submission. Rails automatically wraps
    the fields with errors in divs within the CSS class 
    field_with_errors. Must provide styling in CSS this class.
%>
        <ul>
            <% @user.errors.full_messages.each do |msg| %>
                <li><%= msg %></li>
            <% end %>
        </ul>
    </div>
<% end %>

sample_app/app/views/static_pages/about.html.erb
<% provide(:title, "About") %>
<h1>About</h1>
<p>
    The <a href="http://www.railstutorial.org/"><em>Ruby on Rails
            Tutorial</em></a> is a 
        <a href="http://www.railstutorial.org/book">book</a> and
        <a href="http://screencasts.railstutorial.org/">screencast
            series</a> to teach web development with
        <a href="http://rubyonrails.org/">Ruby on Rails</a>.
        This is the sample application for the tutorial.
</p>

sample_app/app/views/static_pages/contact.html.erb
<% provide(:title, 'Contact') %>
<h1>Contact</h1>
<p>
    Contact the Ruby on Rails Tutorial about the sample app at the
    <a href="http://www.railstutorial.org/contact">contact page</a>
</p>

sample_app/app/views/static_pages/help.html.erb
<% provide(:title, "Help") %>
<h1>Help</h1>
<p>
    Get help on the Ruby on Rails Tutorial at the
    <a href="http://www.railstutorial.org/help">
        Rails Tutorial help page</a>. To get help
    on this sample app, see the 
    <a href="http://www.railstutorial.org/book">
        <em>Ruby on Rails Tutorial</em>book</a>
</p>

sample_app/app/views/static_pages/home.html.erb
<div class="center jumbotron">
    <h1>Welcome to the Sample App</h1>
    <h2>This is the home page for the
        <a href="http://www.railstutorial.org/">
        Ruby on Rails Tutorial</a> sample
        application.
    </h2>

    <%= link_to "Sign up now!", signup_path, class: "btn btn-lg
                 btn-primary"%>
</div>

<%= link_to image_tag("rails.png", alt: "Rails logo"),
                'http://rubyonrails.org/' %>

sample_app/app/views/users/new.html.erb
<% provide(:title, 'Sign up') %>
<h1>Sign up</h1>

<div class="row">
    <div class="col-md-6 col-md-offset-3">
        <%# form_for(@user) allows Rails to infer that
            the action of the form should be to POST to
            the URL /users %>
        <%= form_for(@user) do |f| %>
            <%= render 'shared/error_messages' %>

            <%= f.label :name %>
            <%= f.text_field :name, class: 'form-control' %>

            <%= f.label :email %>
            <%= f.email_field :email, class: 'form-control' %>

            <%= f.label :password %>
            <%= f.password_field :password, class: 'form-control'%>

            <%= f.label :password_confirmation, "Confirmation" %>
            <%= f.password_field :password_confirmation, class: 'form-control' %>

            <%= f.submit "Create my account", class: "btn btn-primary" %>

        <% end %>
    </div>
</div>

sample_app/app/views/users/show.html.erb
<% provide(:title, @user.name) %>
<div class="row">
    <aside class="col-md-4">
        <section class="user_info">
            <h1>
                <%= gravatar_for @user %>
                <%= @user.name %>
            </h1>
        </section>
    </aside>
</div>